// PROJECTS
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const SET_PROJECT_SUCCESS = 'SET_PROJECT_SUCCESS';
export const REMOVE_PROJECT_SUCCESS = 'REMOVE_PROJECT_SUCCESS';
export const EDITING_PROJECT_SUCCESS = 'EDITING_PROJECT_SUCCESS';
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';

// TASKS
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const SET_TASK_SUCCESS = 'SET_TASK_SUCCESS';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';
export const EDITING_TASK_SUCCESS = 'EDITING_TASK_SUCCESS';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_STATUS_SUCCESS = 'EDIT_TASK_STATUS_SUCCESS';

